---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian-12
    image: geerlingguy/docker-debian12-ansible
    pre_build_image: true
  - name: ubuntu-22_04
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
